language: python
sudo: false

services:
    - docker

env:
    global:
        - secure: br4/uA6kM7/aiO9c4/uKrn0PCYHa8NTD/DV98N8K1/YHb5HGbOhIVrV7F7GBKiGOQKIwuD7hZ9fmZeI80iDjIdBfP+rlUt3Ipdd6/X+IwcHu46t9N89Fuw6EK+KApjK3et1BXvqT8GPMjOLX9a2O58fYMMr6OBPQGPDdSNCLnE7PQ1kX79WtXI/YpF3Ip5mDDrOeOOddVpS6+biHBthrdYRK/ZZJDTVt1HmL3Oe9LF8vt9Xw3JdzHnwBTuWg1mI+z0UCD7Nsylls/zxg8uORaMKnDIem9D9oIFWcLFWP9U/rqkIaoDi5XNwVWvMEmBT9D2qRfthm4yGyMFaBTbmE/JPG1bVuYgZYnz9DXRacRW978NudAYE7VOHjom89cW5sEt2525RbXtTgS53hZP+0PKwouXGvZPh+S45uSzKAuiCuXAuwRMLC9P77KKy+2ouhD0Czbz6BoBUtF8/KkTCQyxfo4h96+l3aVaCfD10LA3dRPJI2lWozvi57PmFvHVfKwN4B+aNunFvfuQhVdVZbudnKlFO0ew4AFaIZlKc35QeG8Yi7aymOeg+d2GsCpYG9blvMgF4+2K1Zt1OGbaO+cOhY3rI5pE6PRKQKfcpUaOLXhozLVBCMNJmXmbevuTwV6JK9UYnNRW7oVNfAbnox63PkfQIVC8LIJ7i21f/qjAU=
        - secure: Nwuuh9hk3JhmoPDQG5hCt5dOvQnwOQm0SkQsHbE9PHWMZSftysM/dig80qmdoB4JfcB+0OzXFPJwBZC+IMePzjEsGcP4p2BgEnYmDS3TrPcSiPAljqvOiNj/0/K7I74ZgLm4UtnRjM6m1Og4p8+ueOHXJIiOXMmd6O2njwFcrEk9zFOrYyNLCv6OfnOQDG8E9MFuV5uoHGyr4aurjdZNRj+Io6ENbatWBXCeFTh/XuDNDrCyBrB0FkRah2jF8JMi5hU+FQI78ZnXJxGhSabyEZhPRdPEPI2FHFSn3tEiaoRQghksIR9SNfz86HqZ488BBLttBPkl9m9TbXi9ZczjagkMS5mpQ5z2HNb0Jy5brlKVkfZQry/cmIoFZHWvNzUnCM6QzaQbmsinpC9BKdnllpQfRlE/Z4jzfVLeHCvOvJu8xrGj0LsVslJZTO2g2zZkbrH0myfiV3WHIKZW+IbblqtYIN3FlT8UMnK80TJKNqP1FYU4TAg15ZNtxcr9DTi4ybLm7+c4s+Blb3UNDzhP2IfUSLnLSs/5mPhXsg+CQXAYX6ZES50XH5HCLDPUsodfI1uVEyisOKYGyFh1/ggpXJagGCAc1b9DIAriYs347fZc1OrplUtzDFQmxEpW5kGlnC3vdfALYOTejUZX2OLWLJ1rfRhfcwoWOXc++T8lqvY=
    matrix:
        - VERSION=0.9-composable
        - VERSION=1.0-composable
        - VERSION=1.1-composable
        - VERSION=latest-composable

before_script:
    - cd ${VERSION}
    - cp ../hub-docs/docker-compose.yml ../hub-docs/nginx.conf .
    - sed -i 's/latest-composable/${VERSION}/' docker-compose.yml

script:
    - docker build -t fiware/wirecloud:${VERSION} .
    - docker-compose up -d
    - sleep 40
    - curl -v http://localhost/api/version

after_success:
    - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push fiware/wirecloud:${VERSION}

branches:
    only:
        - master
