language: python
sudo: false

services:
    - docker

env:
    - VERSION=0.9-composable
    - VERSION=1.0-composable
    - VERSION=1.1-composable

before_script:
    - cd ${VERSION}
    - cp ../hub-docs/docker-compose.yml ../hub-docs/nginx.conf .
    - sed -i 's/latest-composable/${VERSION}-composable/' docker-compose.yml

script:
    - docker build -t fiware/wirecloud:${VERSION} .
    - docker-compose up -d
    - curl -v http://localhost/api/version
    - docker stop container

after_success:
    - test $TRAVIS_PULL_REQUEST != "false" && docker push fiware/wirecloud:${VERSION}

branches:
    only:
        - master
