version: "3"

services:

    wirecloud:
        restart: always
        image: fiware/wirecloud:1.3
        ports:
            - 80:8000
        environment:
            - DEBUG=True
        volumes:
            - ./wirecloud-data:/opt/wirecloud_instance/data
            - ./wirecloud-static:/var/www/static
