nginx:
    restart: always
    image: nginx:latest
    ports:
        - 80:80
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
        - wirecloud
    links:
        - wirecloud:wirecloud


postgres:
    restart: always
    image: postgres:latest
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    ports:
        - 127.0.0.1:5432:5432


wirecloud:
    restart: always
    image: fiware/wirecloud:latest-composable
    links:
        - postgres:postgres
    ports:
        - 127.0.0.1:8000:8000
    volumes:
        - ./wirecloud_instance:/opt/wirecloud_instance
        - ./static:/var/www/static
